services:
  sb-api:
    image: jacobbermudes/sbapi:alpha0.5
    container_name: sb-api
    restart: always
    ports:
      - "9090:9090"
    environment:
      - I_GBG=${I_GBG}
      - API_SECRET=${API_SECRET}
      - JWT_SECRET=${JWT_SECRET}
      - PSQL_USER=${PSQL_USER}
      - PSQL_PASS=${PSQL_PASS}
      - PSQL_DB=${PSQL_DB}
      - FF_APIKEY=${FF_APIKEY}
      - FF_APISECRET=${FF_APISECRET}
      - CRYPTOWALLET=${CRYPTOWALLET}
      - X-CMC_PRO_API_KEY=${X-CMC_PRO_API_KEY}
    depends_on:
      - db
    networks:
      - surfboost
    
  db:
    image: postgres:18.3-alpine
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    networks:
      - surfboost 
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  surfboost:
    driver: bridge
