services:
  sb-api:
    image: jacobbermudes/sbapi:alpha0.7
    container_name: sb-api
    restart: always
    ports:
      - "9090:9090"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - surfboost
    
  db:
    image: postgres:18.3-alpine
    container_name: psql
    restart: always
    environment:
      POSTGRES_USER: ${PSQL_USER}
      POSTGRES_PASSWORD: ${PSQL_PASS}
      POSTGRES_DB: ${PSQL_DB}
    networks:
      - surfboost 
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:

networks:
  surfboost:
    driver: bridge
